title: Stezka Češov Veselí - spolek
description: Stránky o naučné stezce 
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

url: "https://tomaskulhanek.github.io/stezka-cesov-veseli"

aux_links:
